path: "/content/data" # dataset root dir
train: train.txt # train images (relative to 'path')
val: train.txt # val images (relative to 'path')
test: test.txt

# Classes
names:
  0: person
  1: people
